name: Docker CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

       # Login Docker Hub
      - name: Login Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build image
      - name: Build image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/demo:${{ github.run_number }} .

      # Push image
      - name: Push image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/demo:${{ github.run_number }}
